// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4GqqMVVKdhUwMctcsDMgGij0Yp3ga8Sg',
    appId: '1:883135759640:web:a765c74005f59b54a74a6d',
    messagingSenderId: '883135759640',
    projectId: 'medpass3',
    authDomain: 'medpass3.firebaseapp.com',
    storageBucket: 'medpass3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6ocrLwMc2eektOzvmeUBII4-OCfGenI',
    appId: '1:883135759640:android:36e517fcab4261d5a74a6d',
    messagingSenderId: '883135759640',
    projectId: 'medpass3',
    storageBucket: 'medpass3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzRWga29m_nyWAfoUsuOhEAH_EDXFoZI',
    appId: '1:883135759640:ios:b4491da3783c86b3a74a6d',
    messagingSenderId: '883135759640',
    projectId: 'medpass3',
    storageBucket: 'medpass3.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtzRWga29m_nyWAfoUsuOhEAH_EDXFoZI',
    appId: '1:883135759640:ios:b4491da3783c86b3a74a6d',
    messagingSenderId: '883135759640',
    projectId: 'medpass3',
    storageBucket: 'medpass3.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4GqqMVVKdhUwMctcsDMgGij0Yp3ga8Sg',
    appId: '1:883135759640:web:78304ed05c1157fea74a6d',
    messagingSenderId: '883135759640',
    projectId: 'medpass3',
    authDomain: 'medpass3.firebaseapp.com',
    storageBucket: 'medpass3.firebasestorage.app',
  );
}
